beta: nat
lr: 0.05
monte_carlo_gp_samples: 128
threshold_parameter: 0.95
reg_weighting: 10.0

run_name: run
write_to_resume: false
M_batch: 0

symmetricality_constraint: true
remove_uniform: false
include_pi_u_tilde: true
swap_type: full
shared_swap_function: false
shared_emission_distribution: false
fix_non_swap: true
include_pi_1_tilde: false
fix_inducing_point_locations: true
init_min_seps: true
R_per_dim: 18
kernel_type: weiland
inducing_point_variational_parameterisation_type: gaussian # gaussian = eq12 or vanilla = eq11, ignored if swap_type == 'spike_and_slab'
