num_training_examples: 5000
beta: nat
lr: 0.1
monte_carlo_gp_samples: 64
threshold_parameter: 0.95
reg_weighting: 10.0

run_name: run
write_to_resume: false
M_batch: 0
symmetricality_constraint: true

remove_uniform: false
include_pi_u_tilde: true
swap_type: full
shared_swap_function: false
shared_emission_distribution: false
fix_non_swap: true
include_pi_1_tilde: false
fix_inducing_point_locations: false
init_min_seps: false
R_per_dim: 18
kernel_type: weiland
inducing_point_variational_parameterisation_type: gaussian # gaussian = eq12 or vanilla = eq11, ignored if swap_type == 'spike_and_slab'

delta_smoother_kappa: 25.0
initial_distribution_kappa: 30.0
residual_deltas_update_frequency: 500